FROM node:18-alpine AS sveltefly-dev

ENV NODE_ENV development

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install

COPY . .


EXPOSE 3000
EXPOSE 24678


CMD ["npm", "run", "dev"]
