version: "3"

services:
  external:
    container_name: external
    image: sveltefly-app
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Zurich
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
